### ISSUE TITLE
etcd - panic: runtime error

### ISSUE THREAD

**Issue by strus38** [fabric8pio/kubernetes-installer-rpi#4]
Trying to deploy on RPi2 and RPi3 mix...  any idea?

```
 docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                  PORTS               NAMES
f500db8ca51b        etcd                                   "etcd --data-dir=/var"   1 seconds ago       Up Less than a second                       k8s_etcd.23d7fc08_kube-controller-black-pearl_default_2d7688bceff12d2c89bf40c848f6e4dd_da716357
e2c6a80cd35c        hyperkube                              "/hyperkube proxy --m"   24 hours ago        Up 24 hours                                 k8s_kube-proxy.77350919_kube-controller-black-pearl_default_2d7688bceff12d2c89bf40c848f6e4dd_1f535227
4e786b0f22f1        hyperkube                              "/hyperkube scheduler"   24 hours ago        Up 24 hours                                 k8s_kube-scheduler.9eefe01e_kube-controller-black-pearl_default_2d7688bceff12d2c89bf40c848f6e4dd_d35339c1
d1b3b6986094        gcr.io/google_containers/pause:0.8.0   "/pause"                 24 hours ago        Up 24 hours                                 k8s_POD.e4cc795_kube-controller-black-pearl_default_2d7688bceff12d2c89bf40c848f6e4dd_6392fc7c
```

```
$ docker logs f500db8ca51b
2016-06-28 21:10:26.672798 W | etcdmain: running etcd on unsupported architecture "arm" since ETCD_UNSUPPORTED_ARCH is set
2016-06-28 21:10:26.676525 W | flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=arm
2016-06-28 21:10:26.676882 I | etcdmain: etcd Version: 3.0.0-beta.0+git
2016-06-28 21:10:26.676999 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2016-06-28 21:10:26.677096 I | etcdmain: Go Version: go1.5
2016-06-28 21:10:26.677272 I | etcdmain: Go OS/Arch: linux/arm
2016-06-28 21:10:26.677595 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-06-28 21:10:26.678862 I | etcdmain: listening for peers on http://127.0.0.1:2380
2016-06-28 21:10:26.679380 I | etcdmain: listening for client requests on 127.0.0.1:2379
2016-06-28 21:10:26.792411 I | etcdserver: name = etcd
2016-06-28 21:10:26.792950 I | etcdserver: data dir = /var/lib/etcd
2016-06-28 21:10:26.793381 I | etcdserver: member dir = /var/lib/etcd/member
2016-06-28 21:10:26.793744 I | etcdserver: heartbeat = 100ms
2016-06-28 21:10:26.794112 I | etcdserver: election = 1000ms
2016-06-28 21:10:26.794447 I | etcdserver: snapshot count = 10000
2016-06-28 21:10:26.794864 I | etcdserver: advertise client URLs = http://127.0.0.1:2379
2016-06-28 21:10:26.795104 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2016-06-28 21:10:26.795315 I | etcdserver: initial cluster = etcd=http://localhost:2380
2016-06-28 21:10:26.844621 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2016-06-28 21:10:26.846190 I | raft: 8e9e05c52164694d became follower at term 0
2016-06-28 21:10:26.846717 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-06-28 21:10:26.846915 I | raft: 8e9e05c52164694d became follower at term 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x34e0d4]

goroutine 1 [running]:
sync/atomic.storeUint64(0x112e4104, 0x0, 0x0)
    /goroot1.5/src/sync/atomic/64bit_arm.go:20 +0x40
github.com/coreos/etcd/etcdserver.(*consistentIndex).setConsistentIndex(0x112e4104, 0x0, 0x0)
    /gopath1.5/src/github.com/coreos/etcd/etcdserver/consistent_index.go:28 +0x2c
github.com/coreos/etcd/etcdserver.NewServer(0x111c0160, 0x112e4000, 0x0, 0x0)
    /gopath1.5/src/github.com/coreos/etcd/etcdserver/server.go:405 +0x1a84
github.com/coreos/etcd/etcdmain.startEtcd(0x1119a1e0, 0x0, 0x0, 0x0)
    /gopath1.5/src/github.com/coreos/etcd/etcdmain/etcd.go:366 +0x25cc
github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
    /gopath1.5/src/github.com/coreos/etcd/etcdmain/etcd.go:125 +0x9c8
github.com/coreos/etcd/etcdmain.Main()
    /gopath1.5/src/github.com/coreos/etcd/etcdmain/main.go:36 +0x1c0
main.main()
    /gopath1.5/src/github.com/coreos/etcd/main.go:28 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /goroot1.5/src/runtime/asm_arm.s:1036 +0x4

goroutine 86 [syscall]:
os/signal.loop()
    /goroot1.5/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
    /goroot1.5/src/os/signal/signal_unix.go:28 +0x30

goroutine 82 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0x111105c0)
    /gopath1.5/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x6c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
    /gopath1.5/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc4

goroutine 44 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0x111531e0)
    /gopath1.5/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x6c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
    /gopath1.5/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc4

goroutine 96 [runnable]:
github.com/coreos/etcd/mvcc/backend.(*backend).run(0x1119ca50)
    /gopath1.5/src/github.com/coreos/etcd/mvcc/backend/backend.go:185 +0x184
created by github.com/coreos/etcd/mvcc/backend.newBackend
    /gopath1.5/src/github.com/coreos/etcd/mvcc/backend/backend.go:119 +0x29c

goroutine 97 [select]:
github.com/coreos/etcd/wal.(*filePipeline).run(0x111bd3a0)
    /gopath1.5/src/github.com/coreos/etcd/wal/file_pipeline.go:89 +0x19c
created by github.com/coreos/etcd/wal.newFilePipeline
    /gopath1.5/src/github.com/coreos/etcd/wal/file_pipeline.go:47 +0x15c

goroutine 98 [select]:
github.com/coreos/etcd/raft.(*node).run(0x111175c0, 0x1119ed80)
    /gopath1.5/src/github.com/coreos/etcd/raft/node.go:307 +0xfd0
created by github.com/coreos/etcd/raft.StartNode
    /gopath1.5/src/github.com/coreos/etcd/raft/node.go:204 +0x628

goroutine 73 [select]:
github.com/coreos/etcd/lease.(*lessor).runLoop(0x11117680)
    /gopath1.5/src/github.com/coreos/etcd/lease/lessor.go:360 +0x244
created by github.com/coreos/etcd/lease.newLessor
    /gopath1.5/src/github.com/coreos/etcd/lease/lessor.go:163 +0x1a0

goroutine 74 [select]:
github.com/coreos/etcd/pkg/schedule.(*fifo).run(0x11196540)
    /gopath1.5/src/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x29c
created by github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
    /gopath1.5/src/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x284

goroutine 75 [select]:
github.com/coreos/etcd/mvcc.(*watchableStore).syncWatchersLoop(0x110f95e0)
    /gopath1.5/src/github.com/coreos/etcd/mvcc/watchable_store.go:280 +0x234
created by github.com/coreos/etcd/mvcc.newWatchableStore
    /gopath1.5/src/github.com/coreos/etcd/mvcc/watchable_store.go:84 +0x390

goroutine 76 [select]:
github.com/coreos/etcd/mvcc.(*watchableStore).syncVictimsLoop(0x110f95e0)
    /gopath1.5/src/github.com/coreos/etcd/mvcc/watchable_store.go:306 +0x1d0
created by github.com/coreos/etcd/mvcc.newWatchableStore
    /gopath1.5/src/github.com/coreos/etcd/mvcc/watchable_store.go:85 +0x3ac
```

```
$ docker info
Containers: 39
 Running: 3
 Paused: 0
 Stopped: 36
Images: 21
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.1.12-hypriotos-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 925.5 MiB
```

**Comment by rschellius** [comment]
Could this be a 32 vs 64 bit issue between RP2 and RP3? I think I read that mixing the two is not advised.
